<?php
/**
 * BizCity CRM — Campaign Ref Codec (PHASE 0.35 M6.W10).
 *
 * Encodes/decodes the Messenger / QR `ref=camp_<token>` parameter that the
 * FB Messenger adapter receives on referral. Token is short (≤12 chars) so it
 * fits comfortably in a printed QR code.
 *
 * Design (R-CMP-2):
 *   - If legacy helper `twf_encrypt_chat_id()` (waic_twf) is loaded → reuse it
 *     so links generated by `bizgpt_flows` keep working after a campaign is
 *     imported via `BizCity_CRM_Flow_Importer`.
 *   - Otherwise → HMAC-SHA1(secret, id) truncated to 12 base62 chars +
 *     reverse-lookup table cached in `wp_options['bizcity_crm_ref_map']`.
 *
 * Properties:
 *   - encode(decode(token)) === id   (round-trip)
 *   - distinct ids → distinct tokens (collision check on insert)
 *   - tokens never embed plain id (privacy + spider protection)
 *
 * @package BizCity_Twin_CRM
 * @since   PHASE 0.35 (M6.W10)
 */

defined( 'ABSPATH' ) || exit;

final class BizCity_CRM_Campaign_Ref_Codec {

	const PREFIX        = 'camp_';
	const TOKEN_LEN     = 12;
	const OPTION_MAP    = 'bizcity_crm_ref_map';
	const OPTION_LEGACY = 'bizcity_crm_legacy_ref_map';

	/* ------------------------------------------------------------------
	 * Public API
	 * ------------------------------------------------------------------ */

	/**
	 * Encode a campaign ID to its ref token.
	 *
	 * **PRIMARY format (2026-05-26)**: `twf_encrypt_chat_id($campaign_id)` —
	 * AES-256-CBC ciphertext, URL-safe base64, NO prefix. This matches the
	 * legacy `mu-plugins/biz-id.php` codec so existing FB ads / sprintads
	 * embedding `?ref=<twf_ciphertext>` continue to resolve without URL edits.
	 *
	 * **Fallback** (only if `twf_encrypt_chat_id` is not loaded): HMAC-SHA1 →
	 * base62 (`camp_<12char>` token), stored in `wp_options['bizcity_crm_ref_map']`.
	 *
	 * @param int  $campaign_id  Positive integer.
	 * @param bool $with_prefix  Legacy param — kept for API back-compat. In twf
	 *                            mode this is IGNORED (twf ciphertext has no
	 *                            prefix). In fallback mode controls `camp_` prefix.
	 * @return string Ref token, or empty string if $campaign_id is invalid.
	 */
	public static function encode( int $campaign_id, bool $with_prefix = true ): string {
		if ( $campaign_id <= 0 ) {
			return '';
		}

		// [2026-08-20 Johnny Chu] CODEC-CORE — standard flow codec preserves the historical URL wire format without twf runtime calls.
		if ( class_exists( 'BizCity_CG_Flow_Ref_Codec' ) ) {
			$tok = BizCity_CG_Flow_Ref_Codec::encode( $campaign_id, 'vietqr' );
			if ( $tok !== '' ) {
				return $tok;
			}
		}

		// === FALLBACK: HMAC base62 + reverse-lookup map ===
		$map   = self::map();
		$token = $map['by_id'][ $campaign_id ] ?? '';

		if ( $token === '' ) {
			$token = self::derive_token( $campaign_id );
			// Cycle on collision until unique (paranoia — HMAC collisions at 12 b62 chars are <1e-15).
			$attempt = 0;
			while ( isset( $map['by_token'][ $token ] ) && (int) $map['by_token'][ $token ] !== $campaign_id ) {
				$attempt++;
				if ( $attempt > 8 ) {
					// Fall back to random — should never happen.
					$token = wp_generate_password( self::TOKEN_LEN, false, false );
				} else {
					$token = self::derive_token( $campaign_id, $attempt );
				}
			}
			$map['by_id'][ $campaign_id ] = $token;
			$map['by_token'][ $token ]    = (string) $campaign_id;
			update_option( self::OPTION_MAP, $map, false );
		}

		return $with_prefix ? self::PREFIX . $token : $token;
	}

	/**
	 * Decode a ref token back to a campaign ID.
	 *
	 * Resolution order (2026-05-26):
	 *   1. **twf_decrypt_chat_id($raw)** — handles both NEW format (encrypted
	 *      campaign_id) and LEGACY ads (encrypted bizgpt_flow_id). If the
	 *      decrypted int matches a row in `bizcity_crm_campaigns.id` → return
	 *      directly. Else look up `imported_from_bizgpt_flow_id = decrypted` →
	 *      return mapped campaign id (so legacy ad URLs still work after
	 *      Flow → Campaign import).
	 *   2. Strip `camp_` prefix → lookup native map (`bizcity_crm_ref_map`).
	 *   3. Lookup legacy map (`bizcity_crm_legacy_ref_map`).
	 *   4. Last-resort scan using HMAC derivation.
	 *
	 * @param string $ref Raw ref param (twf ciphertext, `camp_<token>`, or bare token).
	 * @return int        Campaign ID, or 0 if not found.
	 */
	public static function decode( string $ref ): int {
		$raw = trim( $ref );
		if ( $raw === '' ) {
			return 0;
		}

		// === 0. Plain numeric input (already-decrypted via webhook adapter) ===
		// FB webhook hands us `ref_decrypted = "13"` after twf_decrypt; bypass
		// the encrypted path and resolve directly. R-DCL-NAME 2026-05-26.
		if ( ctype_digit( $raw ) ) {
			$num = (int) $raw;
			if ( $num > 0 ) {
				if ( self::campaign_id_exists( $num ) ) {
					return $num;
				}
				$mapped = self::campaign_id_for_imported_flow( $num );
				if ( $mapped > 0 ) {
					return $mapped;
				}
			}
		}

		// [2026-08-20 Johnny Chu] CODEC-CORE — standard flow codec reads historical URL tokens without twf runtime calls.
		if ( class_exists( 'BizCity_CG_Flow_Ref_Codec' ) ) {
			$decoded = (int) BizCity_CG_Flow_Ref_Codec::decode( $raw, 'vietqr' );
			if ( $decoded > 0 ) {
				// 1a. Is it a campaign id directly?
				if ( self::campaign_id_exists( $decoded ) ) {
					return $decoded;
				}
				// 1b. Legacy ad: decoded is a bizgpt_flow_id → look up imported campaign.
				$mapped = self::campaign_id_for_imported_flow( $decoded );
				if ( $mapped > 0 ) {
					return $mapped;
				}
			}
		}

		// === 2. Fallback to HMAC-base62 token path ===
		$token = self::strip_prefix( $raw );
		if ( $token === '' ) {
			return 0;
		}

		$map = self::map();
		if ( isset( $map['by_token'][ $token ] ) ) {
			return (int) $map['by_token'][ $token ];
		}

		$legacy = self::legacy_map();
		if ( isset( $legacy[ $token ] ) ) {
			return (int) $legacy[ $token ];
		}

		$found = self::scan_legacy_match( $token );
		if ( $found > 0 ) {
			$legacy[ $token ] = (string) $found;
			update_option( self::OPTION_LEGACY, $legacy, false );
			return $found;
		}

		return 0;
	}

	/* ------------------------------------------------------------------
	 * twf-helpers (small wrappers, cached via wp_cache)
	 * ------------------------------------------------------------------ */

	private static function campaign_id_exists( int $id ): bool {
		global $wpdb;
		if ( $id <= 0 || ! class_exists( 'BizCity_CRM_DB_Installer_V2' ) ) { return false; }
		$tbl = BizCity_CRM_DB_Installer_V2::tbl_campaigns();
		return (int) $wpdb->get_var( $wpdb->prepare( "SELECT 1 FROM {$tbl} WHERE id = %d LIMIT 1", $id ) ) === 1;
	}

	private static function campaign_id_for_imported_flow( int $flow_id ): int {
		global $wpdb;
		if ( $flow_id <= 0 || ! class_exists( 'BizCity_CRM_DB_Installer_V2' ) ) { return 0; }
		$tbl = BizCity_CRM_DB_Installer_V2::tbl_campaigns();
		return (int) $wpdb->get_var( $wpdb->prepare(
			"SELECT id FROM {$tbl} WHERE imported_from_bizgpt_flow_id = %d AND deleted_at IS NULL LIMIT 1",
			$flow_id
		) );
	}

	/**
	 * Register a legacy mapping (called by Flow_Importer after import).
	 *
	 * @param string $legacy_token Token previously generated by twf_encrypt_chat_id.
	 * @param int    $campaign_id  Newly-imported campaign ID.
	 */
	public static function register_legacy( string $legacy_token, int $campaign_id ): void {
		$legacy_token = self::strip_prefix( $legacy_token );
		if ( $legacy_token === '' || $campaign_id <= 0 ) {
			return;
		}
		$legacy = self::legacy_map();
		$legacy[ $legacy_token ] = (string) $campaign_id;
		update_option( self::OPTION_LEGACY, $legacy, false );
	}

	/**
	 * Forget a campaign's mapping (on hard delete). Soft-delete keeps mapping
	 * so old QR scans still resolve to the archived campaign for reporting.
	 */
	public static function forget( int $campaign_id ): void {
		$map = self::map();
		$token = $map['by_id'][ $campaign_id ] ?? '';
		if ( $token !== '' ) {
			unset( $map['by_id'][ $campaign_id ], $map['by_token'][ $token ] );
			update_option( self::OPTION_MAP, $map, false );
		}
	}

	/* ------------------------------------------------------------------
	 * Internals
	 * ------------------------------------------------------------------ */

	private static function strip_prefix( string $ref ): string {
		$ref = trim( $ref );
		if ( $ref === '' ) { return ''; }
		if ( strpos( $ref, self::PREFIX ) === 0 ) {
			$ref = substr( $ref, strlen( self::PREFIX ) );
		}
		// Tokens are base62 — strip anything else.
		return preg_replace( '/[^A-Za-z0-9]+/', '', $ref );
	}

	private static function derive_token( int $campaign_id, int $salt = 0 ): string {
		$secret = self::secret();
		$payload = $campaign_id . ':' . $salt;
		// [2026-08-20 Johnny Chu] CODEC-CORE — preserve campaign HMAC-SHA1 token output through the shared primitive.
		$hmac = BizCity_Codec::hmac_sha1( $payload, $secret, true );
		return self::base62( $hmac, self::TOKEN_LEN );
	}

	private static function secret(): string {
		// AUTH_SALT exists in wp-config.php on every WP install. Fallback to
		// blog-specific option for sites where constants were stripped.
		if ( defined( 'AUTH_SALT' ) && AUTH_SALT && AUTH_SALT !== 'put your unique phrase here' ) {
			return (string) AUTH_SALT . '|bizcity_crm_campaign_ref';
		}
		$opt = get_option( 'bizcity_crm_ref_secret' );
		if ( ! $opt ) {
			$opt = wp_generate_password( 64, true, true );
			update_option( 'bizcity_crm_ref_secret', $opt, false );
		}
		return (string) $opt;
	}

	/**
	 * Convert binary digest to base62, truncated to $len chars.
	 */
	private static function base62( string $bin, int $len ): string {
		$alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
		$num      = '';
		// Convert to hex then to GMP-free base62 via repeated division on a long-int string.
		$hex = bin2hex( $bin );
		// Use BCMath if available for precise arbitrary precision; fall back to GMP, then to truncated hex.
		if ( function_exists( 'bcmod' ) && function_exists( 'bcdiv' ) ) {
			$dec = self::hex2dec_bc( $hex );
			while ( strlen( $num ) < $len && bccomp( $dec, '0' ) > 0 ) {
				$rem = (int) bcmod( $dec, '62' );
				$num = $alphabet[ $rem ] . $num;
				$dec = bcdiv( $dec, '62', 0 );
			}
		} elseif ( function_exists( 'gmp_init' ) ) {
			$dec = gmp_init( $hex, 16 );
			while ( strlen( $num ) < $len && gmp_cmp( $dec, 0 ) > 0 ) {
				list( $dec, $rem ) = gmp_div_qr( $dec, 62 );
				$num = $alphabet[ gmp_intval( $rem ) ] . $num;
			}
		} else {
			// Fallback — hex truncation. Not ideal (fewer bits per char) but always works.
			$num = substr( $hex, 0, $len );
		}
		return str_pad( $num, $len, '0', STR_PAD_LEFT );
	}

	/**
	 * Hex string → arbitrary-length decimal string (BC-only).
	 */
	private static function hex2dec_bc( string $hex ): string {
		$dec = '0';
		$len = strlen( $hex );
		for ( $i = 0; $i < $len; $i++ ) {
			$dec = bcmul( $dec, '16', 0 );
			$dec = bcadd( $dec, (string) hexdec( $hex[ $i ] ), 0 );
		}
		return $dec;
	}

	/**
	 * @return array{by_id:array<int,string>,by_token:array<string,string>}
	 */
	private static function map(): array {
		$raw = get_option( self::OPTION_MAP, array() );
		if ( ! is_array( $raw ) ) {
			$raw = array();
		}
		return array(
			'by_id'    => isset( $raw['by_id'] )    && is_array( $raw['by_id'] )    ? $raw['by_id']    : array(),
			'by_token' => isset( $raw['by_token'] ) && is_array( $raw['by_token'] ) ? $raw['by_token'] : array(),
		);
	}

	/**
	 * @return array<string,string>
	 */
	private static function legacy_map(): array {
		$raw = get_option( self::OPTION_LEGACY, array() );
		return is_array( $raw ) ? $raw : array();
	}

	/**
	 * Scan imported campaigns and check if their legacy flow id encodes to
	 * the unknown token. Cheap when imports are <100; degrades for big shops.
	 */
	private static function scan_legacy_match( string $token ): int {
		global $wpdb;
		$tbl = BizCity_CRM_DB_Installer_V2::tbl_campaigns();
		// Only scan campaigns that came from a bizgpt_flows import.
		$rows = $wpdb->get_results(
			"SELECT id, imported_from_bizgpt_flow_id FROM {$tbl}
			 WHERE imported_from_bizgpt_flow_id IS NOT NULL AND deleted_at IS NULL
			 LIMIT 5000",
			ARRAY_A
		);
		foreach ( (array) $rows as $r ) {
			$flow_id = (int) $r['imported_from_bizgpt_flow_id'];
			if ( $flow_id <= 0 ) { continue; }
			$candidate = self::strip_prefix( class_exists( 'BizCity_CG_Flow_Ref_Codec' ) ? BizCity_CG_Flow_Ref_Codec::encode( $flow_id, 'vietqr' ) : '' );
			if ( $candidate !== '' && hash_equals( $candidate, $token ) ) {
				return (int) $r['id'];
			}
		}
		return 0;
	}
}
