<?php
/**
 * @package    Bizcity_Twin_AI
 * @subpackage Core\Automation
 * @author     Johnny Chu (Chu Hoàng Anh) <Hoanganh.itm@gmail.com>
 * @copyright  2024-2026 BizCity — Made in Vietnam 🇻🇳
 * @license    GPL-2.0-or-later
 *
 * BizCity_Automation_Installer — table provisioner (BE-1).
 *
 * Idempotent. The actual `CREATE TABLE` SQL is generated by
 * `BizCity_Diagnostics_Auto_Create::run( $suffix )` from the JSON contract
 * `core/diagnostics/changelog/core.automation.json`. This installer just:
 *
 *  - Stamps `bizcity_automation_db_version` option;
 *  - Triggers auto-create for each suffix if either the option is stale OR
 *    a target table is missing (heals manually-dropped tables);
 *  - Exposes a public `ensure()` method for use by REST controllers / probes.
 *
 * NEVER write raw `dbDelta` here — schema source-of-truth is JSON (R-DCL).
 */

defined( 'ABSPATH' ) || exit;

final class BizCity_Automation_Installer {

	const DB_VERSION        = '1.13.0'; // [2026-07-21 Johnny Chu] PHASE-ZALOBOT-GROUP W8 R-AUTO-TEMPLATE-ID — template_uuid/template_version/visibility.
	const DB_VERSION_OPTION = 'bizcity_automation_db_version';

	/** Table suffixes (without wp_ prefix) declared in core.automation.json. */
	const TABLE_SUFFIXES = array(
		'bizcity_automation_workflows',
		'bizcity_automation_runs',
		'bizcity_automation_templates', // BE-7
		'bizcity_automation_config_packs', // [2026-07-20 Johnny Chu] PHASE-1-TEMPLATES-AUTOMATION — editable CSV/Sheet packs.
		'bizcity_automation_config_rows',  // [2026-07-20 Johnny Chu] PHASE-1-TEMPLATES-AUTOMATION — row_json/canonical/search_text rows.
	);

	// [2026-06-13 Johnny Chu] HOTFIX — per-blog guard array so switch_to_blog() in multisite cron
	// does not skip ensure() for sub-blogs whose tables were never provisioned.
	private static $checked_blog_ids = array();

	// [2026-06-21 Johnny Chu] HOTFIX — per-blog per-request SHOW TABLES cache.
	// Avoids N×SHOW-TABLES on every cron tick for blogs that DO have tables.
	private static $tables_present_cache = array();

	// [2026-07-24 Johnny Chu] PHASE-DIAG-PERF — bounded retry window so a persistently-failing
	// schema heal (clone-without-marker, a real DDL error, permission issue, …) does not re-run
	// SHOW COLUMNS/SHOW INDEX across all 6 tables on every single admin_init/REST/cron request.
	// See core/diagnostics/docs/PHASE-DIAG-PERF-AUTO-CREATE-AUDIT.md.
	const HEAL_BACKOFF_SECONDS = 300; // 5 minutes
	const HEAL_BACKOFF_OPTION  = 'bizcity_automation_db_heal_backoff_until';

	/**
	 * Check workflows table existence once per blog per request.
	 * Result cached in static property — safe to call from every cron hook.
	 */
	public static function tables_present_cached(): bool {
		$blog_id = (int) get_current_blog_id();
		if ( ! array_key_exists( $blog_id, self::$tables_present_cache ) ) {
			global $wpdb;
			$tbl = $wpdb->prefix . 'bizcity_automation_workflows';
			self::$tables_present_cache[ $blog_id ] = bizcity_tbl_exists( $tbl ); // [2026-06-21 Johnny Chu] R-SHOW-TABLES
		}
		return self::$tables_present_cache[ $blog_id ];
	}

	/** Invalidate tables_present_cached() for current blog (call after ensure/install). */
	public static function invalidate_tables_cache(): void {
		$blog_id = (int) get_current_blog_id();
		unset( self::$tables_present_cache[ $blog_id ] );
		wp_cache_delete( 'bz_automation_tables_' . $blog_id, 'bizcity_tbl' );
		// [2026-07-24 Johnny Chu] PHASE-DIAG-PERF — also drop the cached identity-schema result.
		wp_cache_delete( 'bz_autotplid_' . $blog_id, 'bizcity_tbl' );
	}

	/**
	 * Ensure all automation tables exist + version stamp is current.
	 *
	 * Cheap to call repeatedly:
	 *  - Static `$checked` short-circuits within a single request.
	 *  - Once `bizcity_automation_db_version` option == DB_VERSION, we trust
	 *    the stamp and SKIP `SHOW TABLES LIKE` queries. The presence check
	 *    only runs the FIRST time a new DB_VERSION is encountered (or after
	 *    an admin clears the option via diagnostics rerun).
	 *
	 * To force re-verification (e.g. after manual DROP TABLE in dev):
	 *   delete_option( 'bizcity_automation_db_version' );
	 */
	public static function ensure(): void {
		$blog_id = (int) get_current_blog_id();
		if ( isset( self::$checked_blog_ids[ $blog_id ] ) ) {
			return;
		}

		$stamped = get_option( self::DB_VERSION_OPTION, '' );
		// [2026-07-21 Johnny Chu] PHASE-2-TWIN-GPT-CHANNEL-AUTOMATION — do not trust a stale stamp if template identity columns are missing.
		// [2026-07-24 Johnny Chu] PHASE-DIAG-PERF — cache the identity check so this fast path
		// stays a single cached lookup instead of a live information_schema query every request
		// (this was the root cause of the repeated SHOW COLUMNS/SHOW INDEX spam on every pageload).
		if ( $stamped === self::DB_VERSION
			&& self::all_tables_present_cached()
			&& self::templates_identity_schema_ready_cached() ) {
			// Trust the stamp — no SHOW TABLES on every request.
			self::$checked_blog_ids[ $blog_id ] = true;
			return;
		}

		// [2026-07-24 Johnny Chu] PHASE-DIAG-PERF — if a previous attempt already failed to heal
		// within the backoff window, skip the full 6-table SHOW COLUMNS/SHOW INDEX sweep instead of
		// repeating it on every request. Diagnostics "Chẩn đoán" button (bizcity_auto_create action)
		// or clearing HEAL_BACKOFF_OPTION forces an immediate retry.
		if ( self::within_heal_backoff() ) {
			self::$checked_blog_ids[ $blog_id ] = true;
			return;
		}

		if ( ! class_exists( 'BizCity_Diagnostics_Auto_Create' ) && ! self::load_auto_create_runtime() ) {
			// [2026-06-21 Johnny Chu] HOTFIX — In cron context admin_init never fires.
			// If the diagnostics bootstrap is already loaded (BIZCITY_DIAGNOSTICS_DIR defined),
			// require the two auto-create files directly instead of deferring uselessly.
			if ( defined( 'BIZCITY_DIAGNOSTICS_DIR' ) ) {
				if ( ! class_exists( 'BizCity_Diagnostics_Changelog_Loader' ) ) {
					require_once BIZCITY_DIAGNOSTICS_DIR . 'includes/class-diagnostics-changelog-loader.php';
				}
				require_once BIZCITY_DIAGNOSTICS_DIR . 'includes/class-diagnostics-auto-create.php';
			} else {
				// Auto-create not loaded yet (very early request). Defer to admin_init.
				add_action( 'admin_init', array( __CLASS__, 'ensure_admin_init' ), 1 );
				return;
			}
		}
		self::$checked_blog_ids[ $blog_id ] = true;
		// First time at this DB_VERSION → verify + create missing tables.
		foreach ( self::TABLE_SUFFIXES as $suffix ) {
			BizCity_Diagnostics_Auto_Create::run( $suffix );
		}
		if ( self::all_tables_present() && self::templates_identity_schema_ready() ) {
			update_option( self::DB_VERSION_OPTION, self::DB_VERSION, false );
			self::invalidate_tables_cache(); // [2026-06-21 Johnny Chu] HOTFIX — refresh after install
			self::clear_heal_backoff(); // [2026-07-24 Johnny Chu] PHASE-DIAG-PERF
		} else {
			// [2026-07-24 Johnny Chu] PHASE-DIAG-PERF — heal did not converge (ALTER failed / columns
			// still missing); back off so the NEXT request doesn't immediately repeat the same sweep.
			self::set_heal_backoff();
		}
	}

	/** [2026-07-24 Johnny Chu] PHASE-DIAG-PERF — cached wrapper around templates_identity_schema_ready(). */
	private static function templates_identity_schema_ready_cached(): bool {
		$blog_id = (int) get_current_blog_id();
		$ck      = 'bz_autotplid_' . $blog_id;
		$cached  = wp_cache_get( $ck, 'bizcity_tbl' );
		if ( false !== $cached ) {
			return (bool) $cached;
		}
		$ready = self::templates_identity_schema_ready();
		wp_cache_set( $ck, $ready ? 1 : 0, 'bizcity_tbl', HOUR_IN_SECONDS );
		return $ready;
	}

	/** [2026-07-24 Johnny Chu] PHASE-DIAG-PERF — is a failed heal attempt still cooling down? */
	private static function within_heal_backoff(): bool {
		return (int) get_option( self::HEAL_BACKOFF_OPTION, 0 ) > time();
	}

	/** [2026-07-24 Johnny Chu] PHASE-DIAG-PERF — arm the cooldown after a failed heal attempt. */
	private static function set_heal_backoff(): void {
		update_option( self::HEAL_BACKOFF_OPTION, time() + self::HEAL_BACKOFF_SECONDS, false );
	}

	/** [2026-07-24 Johnny Chu] PHASE-DIAG-PERF — clear the cooldown once healed / on force-repair. */
	private static function clear_heal_backoff(): void {
		if ( get_option( self::HEAL_BACKOFF_OPTION, 0 ) ) {
			delete_option( self::HEAL_BACKOFF_OPTION );
		}
	}

	public static function force_templates_identity_schema(): bool {
		// [2026-07-21 Johnny Chu] PHASE-2-TWIN-GPT-CHANNEL-AUTOMATION — seeders may run after an earlier ensure() short-circuited; repair template identity columns explicitly.
		if ( self::templates_identity_schema_ready() ) {
			return true;
		}
		if ( ! class_exists( 'BizCity_Diagnostics_Auto_Create' ) && ! self::load_auto_create_runtime() ) {
			return false;
		}
		BizCity_Diagnostics_Auto_Create::run( 'bizcity_automation_templates' );
		self::invalidate_tables_cache();
		if ( self::templates_identity_schema_ready() && self::all_tables_present() ) {
			update_option( self::DB_VERSION_OPTION, self::DB_VERSION, false );
			self::clear_heal_backoff(); // [2026-07-24 Johnny Chu] PHASE-DIAG-PERF
		}
		return self::templates_identity_schema_ready();
	}

	private static function load_auto_create_runtime(): bool {
		// [2026-07-21 Johnny Chu] PHASE-2-TWIN-GPT-CHANNEL-AUTOMATION — REST template seeding needs additive schema repair even when diagnostics bootstrap was not loaded.
		$diagnostics_dir = dirname( __DIR__, 2 ) . '/diagnostics/';
		if ( ! defined( 'BIZCITY_DIAGNOSTICS_DIR' ) ) {
			define( 'BIZCITY_DIAGNOSTICS_DIR', $diagnostics_dir );
		}
		if ( ! class_exists( 'BizCity_Diagnostics_Changelog_Loader' ) && is_readable( $diagnostics_dir . 'includes/class-diagnostics-changelog-loader.php' ) ) {
			require_once $diagnostics_dir . 'includes/class-diagnostics-changelog-loader.php';
		}
		if ( ! class_exists( 'BizCity_Diagnostics_Auto_Create' ) && is_readable( $diagnostics_dir . 'includes/class-diagnostics-auto-create.php' ) ) {
			require_once $diagnostics_dir . 'includes/class-diagnostics-auto-create.php';
		}
		return class_exists( 'BizCity_Diagnostics_Changelog_Loader' ) && class_exists( 'BizCity_Diagnostics_Auto_Create' );
	}

	public static function templates_identity_schema_ready(): bool {
		// [2026-07-21 Johnny Chu] PHASE-2-TWIN-GPT-CHANNEL-AUTOMATION — upsert writes these columns; missing columns make reseed insert fail and gallery stay empty.
		global $wpdb;
		$table = $wpdb->prefix . 'bizcity_automation_templates';
		$count = (int) $wpdb->get_var( $wpdb->prepare(
			'SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME IN (%s,%s,%s)',
			$table,
			'template_uuid',
			'template_version',
			'visibility'
		) );
		return $count >= 3;
	}

	public static function ensure_admin_init(): void {
		$blog_id = (int) get_current_blog_id();
		unset( self::$checked_blog_ids[ $blog_id ] ); // reset so ensure() re-verifies for this blog
		self::ensure();
	}

	public static function all_tables_present(): bool {
		global $wpdb;
		foreach ( self::TABLE_SUFFIXES as $suffix ) {
			$full = $wpdb->prefix . $suffix;
			if ( ! bizcity_tbl_exists( $full ) ) { // [2026-06-21 Johnny Chu] R-SHOW-TABLES
				return false;
			}
		}
		return true;
	}

	/** Cached all-table readiness check used by the version fast path. */
	private static function all_tables_present_cached(): bool {
		$blog_id = (int) get_current_blog_id();
		$cache_key = 'bz_automation_tables_' . $blog_id;
		$cached = wp_cache_get( $cache_key, 'bizcity_tbl' );
		if ( false !== $cached ) {
			return (bool) $cached;
		}
		$ready = self::all_tables_present();
		wp_cache_set( $cache_key, $ready ? 1 : 0, 'bizcity_tbl', HOUR_IN_SECONDS );
		return $ready;
	}

	public static function table( string $suffix ): string {
		global $wpdb;
		return $wpdb->prefix . $suffix;
	}
}

// [2026-07-20 Johnny Chu] PHASE-1-TEMPLATES-AUTOMATION — register new DataTable tables in central schema catalog (R-CR).
if ( class_exists( 'BizCity_Schema_Registry' ) ) {
	BizCity_Schema_Registry::register( 'bizcity_automation_config_packs', 'core.automation', BizCity_Automation_Installer::DB_VERSION, BizCity_Automation_Installer::DB_VERSION_OPTION, array( 'BizCity_Automation_Installer', 'ensure' ) );
	BizCity_Schema_Registry::register( 'bizcity_automation_config_rows', 'core.automation', BizCity_Automation_Installer::DB_VERSION, BizCity_Automation_Installer::DB_VERSION_OPTION, array( 'BizCity_Automation_Installer', 'ensure' ) );
}
